[package]
name = "tracseq_rc"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
calamine = "0.22.1"
clap = { version = "4.5.1", features = ["derive"] }
rust_xlsxwriter = "0.38.0"

[dev-dependencies]
tempfile = "3.10.1"
